version: "2"

services:
        ros-demo:
                image: ros-demo
                privelaged: true
                volumes:
                        - .:/tutorial:rw
                environment:
                        - DISPLAY=1.1.1.1:0.0 # Change to your IP address
                network-mode: "host"
                container_name: ros-demo
                command: "/bin/bash --init-file scripts/source-ros.sh"
